geocoder-php/BazingaGeocoderBundle

composer.json
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #105
| License       | MIT
| Doc PR        | ~
=> Add support of Symfony 3.0

DependencyInjection/BazingaGeocoderExtension.php, DependencyInjection/Configuration.php, Resources/doc/index.md, Tests/DependencyInjection/Fixtures/config.yml
=> Updated readme to 5.0

README.md
=> Added note about support for 4.x branch.

Resources/doc/cache.md, Resources/doc/custom-provider.md, Resources/doc/index.md, Resources/doc/plugins.md
I moved the docs into some more files and added tons of missing stuff.
=> Updating the documentation for 5.0

.travis.yml, Resources/doc/cache.md
=> Added docs how to use Symfony cache

DependencyInjection/BazingaGeocoderExtension.php, ProviderFactory/GeoIP2Factory.php, Resources/views/Collector/geocoder.html.twig
- Fixes layout path
- Removes "humanize" filter usage
=> Add compatibility with sf 3.4

Resources/views/Collector/geocoder.html.twig
=> fix toolbar item in profiler menu

Command/GeocodeCommand.php, ProviderFactory/ArcGISOnlineFactory.php, ProviderFactory/BingMapsFactory.php, ProviderFactory/FreeGeoIpFactory.php, ProviderFactory/GeoIP2Factory.php, ProviderFactory/GeoIPsFactory.php, ProviderFactory/GeoPluginFactory.php, ProviderFactory/GeonamesFactory.php, ProviderFactory/GoogleMapsFactory.php, ProviderFactory/HostIpFactory.php, ProviderFactory/IpInfoDbFactory.php, ProviderFactory/IpInfoFactory.php, ProviderFactory/MapQuestFactory.php, ProviderFactory/MapzenFactory.php, ProviderFactory/MaxMindFactory.php, ProviderFactory/NominatimFactory.php, ProviderFactory/OpenCageFactory.php, ProviderFactory/PickPointFactory.php, ProviderFactory/TomTomFactory.php, ProviderFactory/YandexFactory.php, Resources/config/services.yml, Tests/Command/GeocodeCommandTest.php
We should not be using the container.
=> Use constructor injection in commands

BazingaGeocoderBundle.php, DependencyInjection/BazingaGeocoderExtension.php, DependencyInjection/Compiler/FactoryValidatorPass.php
=> Allow you to create a custom factory

Resources/doc/index.md
=> Show in docs how to configure HTTP client

Changelog.md
=> Adding changelog for 5.1.2

Resources/config/services.yml, Tests/Validator/Constraint/AddressValidatorTest.php, Validator/Constraint/Address.php, Validator/Constraint/AddressValidator.php, composer.json
If this will be approved, I'll add it to docs.
And I'm not sure about catching the exception when validating, so I'm open to suggestions.
=> Add address validator constraint

Validator/Constraint/Address.php
When renaming I've missed one spot in #212.
=> Fix default configured service for validator

Changelog.md, Resources/config/services.yml, Tests/Functional/BundleInitializationTest.php
=> Fix using custom vendor location

ProviderFactory/HereFactory.php, Resources/doc/services.md, Tests/Functional/ProviderFactoryTest.php, Tests/Functional/config/provider/here.yml, composer.json
Here provider was available in geocoder library but was not available from the Symfony bundle
=> Exposes Here provider to the bundle

Resources/doc/doctrine.md
Supersedes #218 - rebased and with a better commit message
=> Added missing step in Doctrine documentation

ProviderFactory/FreeGeoIpFactory.php
As of https://github.com/geocoder-php/Geocoder/pull/1010,  free geo ip provider changed to https://freegeoip.app.
=> Update FreeGeoIpFactory with freegeoip.app

DependencyInjection/BazingaGeocoderExtension.php, DependencyInjection/Configuration.php, Plugin/FakeIpPlugin.php, Resources/doc/index.md, Tests/DependencyInjection/ConfigurationTest.php, Tests/Plugin/FakeIpPluginTest.php, composer.json
Add option to use [Faker](https://github.com/fzaninotto/Faker#fakerproviderinternet) for FakeIpPlugin.
=> Add option to use Faker for FakeIpPlugin

ProviderFactory/YandexFactory.php
Package geocoder-php/yandex-provider updated, we can use api_key for yandex-geocoder
=> Adding api_key for the YandexFactory

ProviderFactory/MapboxFactory.php, Tests/Functional/ProviderFactoryTest.php, Tests/Functional/config/provider/mapbox.yml, composer.json
I needed Mapbox for a project so I thought i would contribute and add MapboxFactory for every one. 
I also added the tests and it was all fine for me.
Tell me if it requires any modification in order for this to be merged.
Regards,
=> Add MapboxFactory

.gitignore, .travis.yml, Command/GeocodeCommand.php, DataCollector/DataCollectorSymfonyCompatibilityTrait.php, DataCollector/GeocoderDataCollector.php, Resources/config/services.yml, Tests/Command/GeocodeCommandTest.php, Tests/DependencyInjection/ConfigurationTest.php, Tests/Doctrine/ORM/GeocoderListenerTest.php, Tests/Functional/BundleInitializationTest.php, Tests/Functional/ProviderFactoryTest.php, Tests/Mapping/Driver/AnnotationDriverTest.php, Tests/Validator/Constraint/AddressValidatorTest.php, composer.json, phpstan.neon.dist
=> Fix tests/deprecations and Symfony 5 support

Doctrine/ORM/GeocoderListener.php, Tests/Doctrine/ORM/GeocoderListenerTest.php
=> Skip geocoding if address has not changed

ProviderFactory/LocationIQFactory.php, Resources/doc/services.md, Tests/Functional/ProviderFactoryTest.php, Tests/Functional/config/provider/locationiq.yml, composer.json
=> Add locationIQ provider

ProviderFactory/OpenRouteServiceFactory.php, Resources/doc/services.md, composer.json
This adds a factory for the OpenRouteService provider.
=> Add OpenRouteService factory

.github/workflows/ci.yml
Please check it it is correct to replace the two highest runs or if you want the new testruns as additional runs.
=> tests: add tests for php 8.2

templates/Collector/geocoder.html.twig
=> Use `profiler_dump` instead of `dump`
