geocoder-php/BazingaGeocoderBundle

- Resources/doc/index.md
Geocode result is `AddressCollection`, not `Address`, so we must retrieve address from collection.
> Fix wrong example in docs

- DependencyInjection/BazingaGeocoderExtension.php
@Nyholm after moving parameters from xml to yml you removed service IDs as well.
Now it causes a crash when trying to use fakeIP.
It will be good to merge it soon to prevent those crashes. Also, probably when @willdurand will merge https://github.com/geocoder-php/BazingaGeocoderBundle/pull/150 the issue will stop occurring, as you created new classes there.
> fix fakeIP extension id after removing it from services.xml

- Resources/doc/index.md
Added clarification on the public services link. (I missed seeing this the first time through) Added a Usage link for chaining providers. Added the chaining providers section in Usage and Configuration.
Fixes Issue #163
> Adds Documentation for Chaining Providers

- DataCollector/GeocoderDataCollector.php
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | ~ |
| License | MIT |
| Doc PR | ~ |
The data collector implementing the  "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface" interface without the "reset()" method is deprecated since version 3.4 and will be unsupported in 4.0.
> Fix deprecated Symfony 3.4 Data Collector without reset method

- Resources/doc/doctrine.md
Changed Annotation to Annotations.
Changed Geocodable to Geocodeable.
> Fix Documentation for Doctrine Support

- Resources/views/Collector/geocoder.html.twig
I'm working with queries on differentes locales and I was thinking it could be interesting to get the locale for each query in the profiler
> Add query Locale to profiler

- Tests/Doctrine/ORM/GeocoderListenerTest.php
Our test were failing with google because they introduce a requirement to use api key.
> Use Nominatim instad of google

- Command/GeocodeCommand.php
https://github.com/symfony/symfony/pull/28415
The "Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand" class is deprecated since Symfony 4.2, use "Symfony\Component\Console\Command\Command" with dependency injection instead.
> SF 4.2 Compliance

- DependencyInjection/Configuration.php
> A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.
> Fix another SF 4.2 deprecation

- DependencyInjection/BazingaGeocoderExtension.php
This will help people to leverage autowiring without defining custom aliases in application config.
For example:
```yaml
bazinga_geocoder:
providers:
googleMaps:
factory: Bazinga\GeocoderBundle\ProviderFactory\GoogleMapsFactory
```
```php
<?php
namespace App\Service;
use Geocoder\Provider\Provider;
class MyService
{
private $googleMapsGeocoder;
public function __construct(Provider $googleMapsGeocoder)
{
$this->googleMapsGeocoder = $googleMapsGeocoder;
}
}
```
> Add autowiring bindings by Provider interface + providerName

- Doctrine/ORM/GeocoderListener.php
- Mapping/ClassMetadata.php
- Mapping/Driver/AnnotationDriver.php
- Resources/doc/doctrine.md
- Tests/Doctrine/ORM/GeocoderListenerTest.php
Hello,
Following #217, the `Address` annotation can now be used over a method (a getter).  
The method must be public, and it can has any name / any return type.  
It can't have required arguments, though, otherwise an exception will be thrown to indicate the annotation is erroneously used.
No BC breaks, some documentation was added.
> Address annotation can be used over a getter

- Doctrine/ORM/GeocoderListener.php
- Tests/Doctrine/ORM/GeocoderListenerTest.php
When you have and entity with an optional address field, the listener should only fetch coordinates when the address is actually filled in.
> Skip empty address values in listener

- ProviderFactory/AlgoliaFactory.php
- Resources/doc/services.md
- Tests/Functional/ProviderFactoryTest.php
- Tests/Functional/config/provider/algoliaplaces.yml
- composer.json
This PR was made because i noticed a discrepancy between  geocoder-php/Geocoder listed provider support and here. The same effort was done as part of #207  but it remained unfinished for more than a year. I fixed the option names as requested in CR from @tgalopin and @Nyholm on the #207.
> Add Algolia provider factory

- DependencyInjection/BazingaGeocoderExtension.php
- Tests/Functional/BundleInitializationTest.php
- Tests/Functional/config/cache_without_lifetime.yml
> Allow cache lifetime as null

- Resources/config/services.yml
Fixing:
```
In Definition.php line 271:
[Symfony\Component\DependencyInjection\Exception\OutOfBoundsException]
The index "2" is not in the range [0, 1].
Exception trace:
at /srv/app/vendor/symfony/dependency-injection/Definition.php:271
Symfony\Component\DependencyInjection\Definition->replaceArgument() at /srv/app/vendor/willdurand/geocoder-bundle/DependencyInjection/BazingaGeocoderExtension.php:59
```
> Fix extension cannot replace non-defined argument

- ProviderFactory/GeoIPsFactory.php
- ProviderFactory/MapzenFactory.php
This resolves the deprecation triggering described in #259 while still properly triggering a notice when the provider is explicitly used.
> Only trigger provider deprecation notices when they are explicitly configured -- #259.

- Doctrine/ORM/GeocoderListener.php
when searching for an address that returns no result, an AddressCollection item is returned with no locations inside, which means locations is an empty array, so the next line which reads the first result will cause an exception when there is no location. it is better to use the isEmpty() method of the AddressCollection to no try to access the first entry when there is no such entry
> replace empty() check in listener

- ProviderFactory/AbstractFactory.php
- ProviderFactory/AlgoliaFactory.php
- ProviderFactory/ArcGISOnlineFactory.php
- ProviderFactory/BingMapsFactory.php
- ProviderFactory/FreeGeoIpFactory.php
- ProviderFactory/GeoIPsFactory.php
- ProviderFactory/GeoPluginFactory.php
- ProviderFactory/GeonamesFactory.php
- ProviderFactory/GoogleMapsFactory.php
- ProviderFactory/GoogleMapsPlacesFactory.php
- ProviderFactory/HereFactory.php
- ProviderFactory/HostIpFactory.php
- ProviderFactory/IpInfoDbFactory.php
- ProviderFactory/IpInfoFactory.php
- ProviderFactory/IpstackFactory.php
- ProviderFactory/MapQuestFactory.php
- ProviderFactory/MapboxFactory.php
- ProviderFactory/MapzenFactory.php
- ProviderFactory/MaxMindFactory.php
- ProviderFactory/NominatimFactory.php
- ProviderFactory/OpenCageFactory.php
- ProviderFactory/PickPointFactory.php
- ProviderFactory/TomTomFactory.php
- ProviderFactory/YandexFactory.php
- Resources/config/services.yml
- composer.json
This allows leveraging the new `HttplugClient` of the Symfony HttpClient when possible, instead of having to use static discovery when not using HttplugBundle.
> Allow an HTTP client to be injected via the constructor of providers

- ProviderFactory/GeoIP2Factory.php
According to https://github.com/maxmind/GeoIP2-php/blob/v2.2.0-alpha1/src/WebService/Client.php since day one `user_id` was always expected as an `int` and now when it is strictly typehinted it doesn't allow anything other than `int`.
Spotted this in CI and trying to make it green.
> Fix `user_id` type for GeoIP2Factory

- Mapping/Driver/AnnotationDriver.php
Fixed problem where geocoding was not performed, when the changed entity was proxied by Doctrine.
(Ref: #219)
> Fix annotation metadata driver with Doctrine proxies

- Mapping/Annotations/Address.php
- Mapping/Annotations/Geocodeable.php
- Mapping/Annotations/Latitude.php
- Mapping/Annotations/Longitude.php
- Mapping/Driver/AttributeDriver.php
- Resources/doc/doctrine.md
- Tests/Mapping/Driver/AttributeDriverTest.php
This adds support to use PHP 8 attributes for an entity instead of annotations.
E.G
```php
use Bazinga\GeocoderBundle\Mapping\Annotations as Geocoder;
#[Geocoder\Geocodeable()]
class User
{
#[Geocoder\Address()]
private $address;
#[Geocoder\Latitude()]
private $latitude;
#[Geocoder\Longitude()]
private $longitude;
}
```
> Add support for PHP 8 attributes

- Plugin/FakeIpPlugin.php
- Tests/Plugin/FakeIpPluginTest.php
when local_ip is empty, allow to change all ip with fake one. usefull when we can't predict dev IP when using containers for example
> Allow fake IP works for all IPs

- Plugin/FakeIpPlugin.php
- Tests/Plugin/FakeIpPluginTest.php
- composer.json
- phpstan.neon.dist
- Allow needle to be null;
- Fix @testWith syntax error;
- Remove unnecessary `useFaker` variable;
- Handle `Since fakerphp/faker 1.14: Accessing property "ipv4" is deprecated, use "ipv4()" instead.` deprecation.
> Fix FakeIpPlugin

- Command/GeocodeCommand.php
- Resources/config/services.yml
- Tests/Functional/ProviderFactoryTest.php
This will keep [the command lazy loaded](https://symfony.com/doc/4.4/console/commands_as_services.html#lazy-loading) and prevents triggering deprecations when using [Symfony 6.1](https://github.com/symfony/symfony/blob/6.1/UPGRADE-6.1.md#console)
> Fix deprecations with Symfony 6.1

- .github/workflows/ci.yml
- composer.json
- phpstan-baseline.neon
- src/Command/GeocodeCommand.php
- src/DependencyInjection/Configuration.php
I'm updating some applications to Symfony 7 and one of them uses this bundle.
This PR adds `|| ^7.0` to the allowed Symfony dependencies and also adds the two return types that are mandatory in order to run the code in Symfony 7. I know there's #343 to add types everywhere, but these two small changes are enough to make the bundle work in Symfony 7.
Thanks!
> Allow using Symfony 7 and fix some deprecations

- templates/Collector/geocoder.html.twig
Closes #361 
I'm not sure if there was some color before, as `dump` would show only `int(5)` with sf7 project.
This gets it highlighted.
> fix: [profiler] don't use dump/profiler_dump for number of results
